title:        Framework Oriented Programming
tagline:      A reference for Framework Oriented Programming for iOS/tvOS/macOS/watchOS
baseurl:      "/framework-oriented"
paginate:     1
author:
  name:       Caramba
  # url:        http://carambalabs.github.io
gems:
  - jekyll-paginate
markdown: kramdown