title:        Framework Oriented Programming
tagline:      A reference to build modularized apps for iOS/tvOS/macOS/watchOS
paginate:     1
author:
  name:       "@pepibumur"
  url:        "https://twitter.com/pepibumur"
url: "/" # the base hostname & protocol for your site
gems:
  - jekyll-paginate
  - jemoji
markdown: kramdown
github_repository: "https://gitlab.com/caramba/framework-oriented"
