title:        Framework Oriented Programming
tagline:      A reference for Framework Oriented Programming for iOS/tvOS/macOS/watchOS
baseurl:      ""
paginate:     1
author:
  name:       Caramba
  # url:        http://carambalabs.github.io
gems:
  - jekyll-paginate
  - jemoji
markdown: kramdown

github_repository: "https://github.com/carambalabs/framework-oriented"
project_zip: "https://github.com/carambalabs/framework-oriented/archive/master.zip"
